# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
AllCops:
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "tmp/**/*"
    - "vendor/bundle/**/*"

Layout/ArgumentAlignment:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true